### ISSUE TITLE
FromDPDKDevice(FLOW_RULES_FILE) only work with DPDK<=21.11

### ISSUE THREAD

**Issue by pogobanane** [tbarbette/fastclick#391]
To make it work with dpdk 22.11, we have to patch a variable in flowruleparser.hh (see [1]).

To make it work with dpdk 23.07, we need additional patches (see [2]).

[1] https://github.com/vmuxIO/vmuxIO/commit/b890b881672882977b7e0bc962ab3e23ee45eb3d
[2] https://github.com/vmuxIO/vmuxIO/commit/1a9cab2d24b0470171c68b861f8a56500fbbce2c

**Comment by tbarbette** [comment]
Great ! Thanks ! I'll include them with the proper ifdefs.

Did you do a runtime test or that's just for compilation?

**Comment by pogobanane** [comment]
I did runtime tests with an Intel E810.

**Comment by saftab-rashid** [comment]
Hi, 

I have tried FastClick with dpdk 21.11.9 and it works. Now I am trying to use FastClick with newer dpdk versions, e.g., 24.11. However, while compiling FastClick I am getting the following errors:

../lib/dpdkdevice.cc:1206:28: error: ‘ERR’ was not declared in this scope
 1206 |             RTE_ETHDEV_LOG(ERR,
      |                            ^~~
../lib/dpdkdevice.cc:1206:13: error: ‘RTE_ETHDEV_LOG’ was not declared in this scope
 1206 |             RTE_ETHDEV_LOG(ERR,

Any ideas on how to solve this?
